#!/usr/bin/expect
if {[llength $argv] != 3} {
puts "Usage: ./script.exp server user pass"
exit 1
}
set timeout 5
set server [lindex $argv 0]
set user [lindex $argv 1]
set pass [lindex $argv 2]

spawn ssh -q $user@$server
expect  "(yes/no)?"  { send "yes\r" }
expect  "password:"  { send "$pass\r" }
expect  "$ "  { send "sudo su -\r" }
expect  "# "  { send "yum install expect\r" }
set timeout 10
expect  "Is this ok"  { send "y\r" }
expect  "# "  { send "exit\r" }
